CREATE DATABASE CLIENTE;
USE CLIENTE;

DROP TABLE FICHACLIENTE;
CREATE TABLE FICHACLIENTE(
	ID INT PRIMARY KEY  AUTO_INCREMENT,
	NOMBRE VARCHAR(30),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(50),
    CIUDAD VARCHAR(30),
    SEXO VARCHAR(10),
    SO VARCHAR(40),
    COMENTARIO MEDIUMTEXT
)ENGINE=InnoDB;