DROP DATABASE WAYDO;
CREATE DATABASE WAYDO;
USE WAYDO;


CREATE TABLE LOCALIZACION(
	PAIS VARCHAR(30),
    COMUNIDAD VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    DISTRITO VARCHAR(30),
    
    PRIMARY KEY (DISTRITO)
)ENGINE=InnoDB;


CREATE TABLE PUPILOS(
	NICK VARCHAR(20),
    EMAIL VARCHAR(40),
    TELEFONO INTEGER(13),
    PASSWORD VARCHAR(20),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    FNAC DATE,
    DISTRITO VARCHAR(20),
    
    PRIMARY KEY (NICK),
    FOREIGN KEY (DISTRITO) REFERENCES LOCALIZACION(DISTRITO)
)ENGINE=InnoDB;


CREATE TABLE SENSEIS(
	NICK VARCHAR(20),
    EMAIL VARCHAR(40),
    TELEFONO INTEGER(13),
    PASSWORD VARCHAR(20),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    FNAC DATE,
    DISTRITO VARCHAR(20),
    OBSERVACIONES MEDIUMTEXT,
    
    PRIMARY KEY (NICK),
    FOREIGN KEY (DISTRITO) REFERENCES LOCALIZACION(DISTRITO)
)ENGINE=InnoDB;


CREATE TABLE ACTIVIDADES(
	CODACTIVIDAD VARCHAR(10),
    NOMBRE VARCHAR(20),
    DISTRITO VARCHAR(30),
    SENSEI VARCHAR(20),
    PRECIO DECIMAL(5,2),
    FECHA_INICIO DATETIME, 
    FECHA_FIN DATETIME,
    EDICION INT(4),
    
    PRIMARY KEY (CODACTIVIDAD),
    FOREIGN KEY (DISTRITO) REFERENCES LOCALIZACION(DISTRITO),
    FOREIGN KEY (SENSEI) REFERENCES SENSEIS(NICK)
)ENGINE=InnoDB;


/* 
AQUI ES DONDE DA EL ERROR EL COMANDO:
C:\xampp\htdocs\CFTIC\Proyecto Waydo\waydo> php bin/console doctrine:mapping:import "App\Entity" annotation --path=src/Entity
Property "nick" in "Actividades" was already declared, but it must be declared only once 
Prueba 1:
 - modificar nombres de las claves foraneas para que no coincidan
*/
/* DROP TABLE PUPILOS_ACTIVIDADES; */
CREATE TABLE PUPILOS_ACTIVIDADES(
	NICK_PA VARCHAR(20),
	CODACTIVIDAD_PA VARCHAR(10),
    FOREIGN KEY (NICK_PA) REFERENCES PUPILOS(NICK),
    FOREIGN KEY (CODACTIVIDAD_PA) REFERENCES ACTIVIDADES(CODACTIVIDAD),
    PRIMARY KEY (NICK_PA, CODACTIVIDAD_PA)
)ENGINE=InnoDB;


/* DROP TABLE SENSEIS_ACTIVIDADES; */
CREATE TABLE SENSEIS_ACTIVIDADES(
	NICK_SA VARCHAR(20),
	CODACTIVIDAD_SA VARCHAR(10),
    FOREIGN KEY (NICK_SA) REFERENCES SENSEIS(NICK),
    FOREIGN KEY (CODACTIVIDAD_SA) REFERENCES ACTIVIDADES(CODACTIVIDAD),
    PRIMARY KEY (NICK_SA, CODACTIVIDAD_SA)
)ENGINE=InnoDB;


CREATE TABLE TRANSACCIONES(
	CODTRANSACCION VARCHAR(10),
    CODACTIVIDAD VARCHAR(10),
    EMISOR VARCHAR(20),
    RECEPTOR VARCHAR(20),
    CANTIDAD DECIMAL(5,2),
    ESTADO VARCHAR(15),
    
    PRIMARY KEY (CODTRANSACCION),
    FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES(CODACTIVIDAD),
    FOREIGN KEY (EMISOR) REFERENCES PUPILOS(NICK),
    FOREIGN KEY (RECEPTOR) REFERENCES SENSEIS(NICK)
)ENGINE=InnoDB;
